FROM ubuntu:26.04
## prevent interactive prompts
ARG DEBIAN_FRONTEND=noninteractive

## update repositories, install packages, and then clean up
RUN apt update -y && \
    # grab what we can via standard packages
    apt install -y \
        bash \
        ca-certificates \
        curl \
        git \
        jq \
        passwd \
        tar \
        p7zip-full

#############################################################################
## vim: ft=unix syn=dockerfile ts=4 sw=4 et tw=78:
