#############################################################################
# build markdown to html

# use mkdocs:dev image
FROM mkdocs:dev AS builder

# set work dir
WORKDIR /workspaces

# copy source to build
COPY --chown=vlabs:users . .
RUN mkdocs build

#############################################################################
# build the final image with content

# get base image
FROM httpd:2.4-alpine AS final
WORKDIR /usr/local/apache2/htdocs/

# add metadata via labels
LABEL com.vmware.eocto.version="0.0.1"
LABEL com.vmware.eocto.git.repo="git@gitlab.lab.net:sydney/containers/containers.git"
LABEL com.vmware.eocto.git.commit="DEADBEEF"
LABEL com.vmware.eocto.maintainer.name="Richard Croft"
LABEL com.vmware.eocto.maintainer.email="rcroft@vmware.com"
LABEL com.vmware.eocto.released="9999-99-99"
LABEL com.vmware.eocto.based-on="httpd:2.4-alpine"
LABEL com.vmware.eocto.project="containers/www"

# add user and group
# alpine
#RUN addgroup -S user && adduser -S -s /bin/false -G user user
# ubuntu/etc
#RUN groupadd -r user && useradd -r -s /bin/false -g user user

# reset ownership
#RUN chown -R user:user /usr/local/apache2/htdocs/

# copy the html to wwwroot
COPY --from=builder /workspaces/.site/ ./

#############################################################################
# vim: ft=unix sync=dockerfile ts=4 sw=4 et tw=78:
